### ISSUE TITLE
Code blocks with 3 backticks not highlighted

### ISSUE THREAD

**Issue by ricab** [xy2z/SublimeTwilight#1]
Code blocks marked with \`\`\` are not being highlighted, unless syntax is specified. \`\`\`plain not working either:

![image](https://user-images.githubusercontent.com/6698114/185896792-756c9fc1-e726-46ce-8330-6dc8fefbfa9b.png)

**Comment by ricab** [comment]
I believe this would need another entry like [this one](https://github.com/xy2z/SublimeTwilight/blob/master/Twilight%2B.tmTheme#L632-L641) for `markup.raw.block.fenced.markdown` (although personally I'd prefer it to look the same as the inline code). See https://github.com/SublimeText-Markdown/MarkdownEditing/issues/706.

**Comment by xy2z** [comment]
i have switched to VScode, but PR's are welcome

**Comment by ricab** [comment]
I see. How does one test this from cloned repo?

**Comment by ricab** [comment]
Nevermind, I figured it out.
